# Generated by Django 4.2.23 on 2025-07-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_entry_user_topic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='problem_type',
            field=models.CharField(choices=[('silly', 'Silly Mistake'), ('big', 'Big Mistake'), ('concept', 'Conceptual Error'), ('calc', 'Calculation Mistake'), ('skip', 'Skipped/Unattempted')], default='silly', max_length=10),
        ),
    ]
