# Generated by Django 4.2.23 on 2025-07-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_entry_problem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='priority_choice',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='entry',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='entries/'),
        ),
    ]
