# Generated by Django 4.2.23 on 2025-07-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0007_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
